name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  solver:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/solver-core
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
